# Generated by Django 5.2.4 on 2025-07-07 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('priority', models.FloatField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('enabled', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField()),
                ('level_min', models.IntegerField(blank=True, null=True)),
                ('level_max', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignHasMatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='has_matcher', to='matcher.campaign')),
                ('countries', models.ManyToManyField(blank=True, to='matcher.country')),
                ('items', models.ManyToManyField(blank=True, related_name='has_matcher_items', to='matcher.item')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignDoesNotHaveMatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='does_not_have_matcher', to='matcher.campaign')),
                ('items', models.ManyToManyField(blank=True, related_name='does_not_have_matcher_items', to='matcher.item')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=100, unique=True)),
                ('credential', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('last_session', models.DateTimeField()),
                ('total_spent', models.IntegerField()),
                ('total_refund', models.IntegerField()),
                ('total_transactions', models.IntegerField()),
                ('last_purchase', models.DateTimeField()),
                ('level', models.IntegerField()),
                ('xp', models.IntegerField()),
                ('total_playtime', models.IntegerField()),
                ('language', models.CharField(max_length=10)),
                ('birthdate', models.DateTimeField()),
                ('gender', models.CharField(max_length=10)),
                ('_customfield', models.CharField(blank=True, max_length=100, null=True)),
                ('active_campaigns', models.ManyToManyField(blank=True, related_name='active_players', to='matcher.campaign')),
                ('clan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='matcher.clan')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matcher.country')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matcher.item')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='matcher.playerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('carrier', models.CharField(max_length=100)),
                ('firmware', models.CharField(max_length=100)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='matcher.playerprofile')),
            ],
        ),
    ]
